name: Update Go Report Card

on:
  pull_request:
    branches: ["main"]
  schedule:
   - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: creekorful/goreportcard-action@v1.0
